# Generated by Django 6.0.6 on 2026-06-23 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('accepted', 'Accepted'), ('wrong_answer', 'Wrong Answer'), ('compile_error', 'Compile Error'), ('runtime_error', 'Runtime Error'), ('time_limit', 'Time Limit Exceeded'), ('illegal_import', 'Illegal Import')], default='pending', max_length=20)),
                ('compile_output', models.TextField(blank=True)),
                ('task_id', models.CharField(blank=True, max_length=255)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'submissions',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passed', models.BooleanField()),
                ('actual_output', models.TextField(blank=True)),
                ('error_output', models.TextField(blank=True)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'test_results',
                'ordering': ['test_case__order'],
            },
        ),
        migrations.CreateModel(
            name='UserExerciseProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempts', models.IntegerField(default=0)),
                ('passed', models.BooleanField(default=False)),
                ('first_attempted', models.DateTimeField(auto_now_add=True)),
                ('last_attempted', models.DateTimeField(auto_now=True)),
                ('passed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_exercise_progress',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('checkpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='exercises.checkpoint')),
                ('exercises_completed', models.ManyToManyField(blank=True, related_name='completed_in_sessions', to='exercises.exercise')),
            ],
            options={
                'db_table': 'sessions',
                'ordering': ['-started_at'],
            },
        ),
    ]
