# Generated by Django 6.0.6 on 2026-06-28 03:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_exercise_submit_main_file_and_more'),
        ('submissions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='current_exercise',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_sessions', to='exercises.exercise'),
        ),
        migrations.AddField(
            model_name='session',
            name='current_level_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='level_results',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='session',
            name='timer_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='session',
            name='timer_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
