# Generated by Django 6.0.6 on 2026-06-28 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_session_current_exercise_session_current_level_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
