# Generated by Django 6.0.6 on 2026-06-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_session_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='exercise_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
