# Generated by Django 6.0.6 on 2026-06-23 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Checkpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'checkpoints',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(unique=True)),
                ('file_extension', models.CharField(max_length=10)),
                ('docker_image', models.CharField(max_length=200)),
                ('timeout_seconds', models.IntegerField(default=10)),
                ('memory_limit', models.CharField(default='64m', max_length=20)),
                ('default_forbidden_imports', models.TextField(blank=True, help_text='Comma-separated. e.g. "fmt,os,net/http"')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'languages',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('difficulty_pct', models.IntegerField(help_text='Difficulty percentage (5, 10, 20, 35, 50, 65, 75, 85, 95, 100)')),
                ('forbidden_imports', models.TextField(blank=True, help_text='Comma-separated imports NOT allowed. e.g. "fmt,os". Overrides language defaults.')),
                ('allowed_imports', models.TextField(blank=True, help_text='Comma-separated imports explicitly allowed. e.g. "z01". Leave blank for no restrictions.')),
                ('use_language_forbidden_defaults', models.BooleanField(default=True, help_text='If True, also applies the language-level forbidden imports.')),
                ('starter_code', models.TextField(blank=True, help_text='Boilerplate code shown to student when they open the exercise.')),
                ('xp_reward', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('checkpoint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exercises', to='exercises.checkpoint')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exercises', to='exercises.language')),
            ],
            options={
                'db_table': 'exercises',
                'ordering': ['difficulty_pct', 'name'],
            },
        ),
        migrations.AddField(
            model_name='checkpoint',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='checkpoints', to='exercises.language'),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stdin', models.TextField(blank=True)),
                ('expected_output', models.TextField()),
                ('is_hidden', models.BooleanField(default=False, help_text='Hidden test cases only show pass/fail — no input or expected output revealed.')),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='exercises.exercise')),
            ],
            options={
                'db_table': 'test_cases',
                'ordering': ['exercise', 'order'],
            },
        ),
    ]
