# Generated by Django 6.0.6 on 2026-06-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='main_file',
            field=models.TextField(blank=True, help_text='main.go content — package main, imports piscine, calls functions. Read-only for students.'),
        ),
        migrations.AddField(
            model_name='exercise',
            name='student_filename',
            field=models.CharField(default='solution.go', help_text='Filename for student file e.g. "countalpha.go". Shown as second tab.', max_length=100),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='allowed_imports',
            field=models.TextField(blank=True, help_text='Comma-separated imports explicitly allowed.'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='forbidden_imports',
            field=models.TextField(blank=True, help_text='Comma-separated imports NOT allowed.'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='starter_code',
            field=models.TextField(blank=True, help_text='Boilerplate shown in the student editor tab.'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='use_language_forbidden_defaults',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='testcase',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
