# Generated by Django 6.0.6 on 2026-06-26 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_exercise_main_file_exercise_student_filename_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='submit_main_file',
            field=models.TextField(blank=True, help_text='main.go used during Submit — reads from stdin for proper test case grading. Hidden from student.'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='allowed_imports',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='difficulty_pct',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='forbidden_imports',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='main_file',
            field=models.TextField(blank=True, help_text='main.go shown to student as read-only tab. Uses hardcoded calls for Test button.'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='starter_code',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='student_filename',
            field=models.CharField(default='solution.go', help_text='Filename for student file e.g. "countalpha.go".', max_length=100),
        ),
        migrations.AlterField(
            model_name='language',
            name='default_forbidden_imports',
            field=models.TextField(blank=True),
        ),
    ]
